### ISSUE TITLE
Cambios en Atmosphère 0.18.0

### ISSUE THREAD

**Issue by joepc74** [SpaceNX/Stellar#1]
Atmosphère saco 3 cambios del paquete: https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.18.0
Creo que el ultimo no es el que esta en Stellar, haria falta actualizar el paquete.

**Comment by joepc74** [comment]
Y de paso el Hekate nuevo.

**Comment by SpaceNX** [comment]
@joepc74 Se ha actualizado a la ultima versión, te agradezco que nos informes cualquier inconveniente.
